### ISSUE TITLE
switch between ![]() and <img src=> notation

### ISSUE THREAD

**Issue by anaderi** [tlnagy/atom-markdown-image-assistant#2]
Sometimes (when you need to alter image size) it is more convenient to have <img src=> image reference. Would be great to switch between those by choosing appropriate one from the plugin settings!
Thanks!

**Comment by tlnagy** [comment]
That could be useful indeed, I'm happy to review a PR if you submit one. I'm working on other projects so I don't have time to do this myself at the moment.

**Comment by roblabs** [comment]
I have a prototype fix for this, and I use it to switch back and forth between `![]()` and `<img src=''>` as both are useful.  

@tlnagy, can you review and see if the order of the settings is what you want?  I found it fairly hard to get the order right, but wanted to check with you before the PR comes.

-----
![untitled 39](https://cloud.githubusercontent.com/assets/118112/24257591/81c2ddc4-0fa8-11e7-9430-15eb355ba095.png)

**Comment by tlnagy** [comment]
That looks great!
