### ISSUE TITLE
Customizable upload directory

### ISSUE THREAD

**Issue by fenwick67** [tlnagy/atom-markdown-image-assistant#3]
Hey, I want to use this but would need to change the image upload directory for it to be useful.

Would you accept a PR to use the Atom [config API](https://atom.io/docs/api/v1.14.4/Config) to let users change this from `../assets` to something else?

**Comment by tlnagy** [comment]
Yes, certainly! If you submit a PR, I'll review it and merge.

**Comment by tlnagy** [comment]
Any progress on this?

**Comment by fenwick67** [comment]
I was on vacation last week, will probably work on it sometime this week.
