### ISSUE TITLE
Insert slash in case of backslash in Windows

### ISSUE THREAD

**Issue by mahibi** [tlnagy/atom-markdown-image-assistant#4]
I use markdown in Atom to convert my Notes to HTML with markdown-themeable-pdf. However i have a problem with with the HTML Image-Links when is use atom-markdown-image-assistant:

When i make a screenshot in Linux and paste it to Atom, this will result in a Path with a Slash:
        `![](assets/123image.png)`
Converting with markdown-themeable-pdf to HTML works fine. The resulting Link is:
        `<img src="assets/123image.png" alt="">`
I can view the Images in HTML with Windows and Linux.

But when i make a screenshot in Windows and paste it to Atom, this will result in a Path with a Backslash:
        `![](assets\123image.png)`
Converting with markdown-themeable-pdf to HTML results in a Link with %5C for the Backslash:
        `<img src="assets%5C123image.png" alt="">`
My Problem is that these pictures won't show up when opening this HTML-File with Linux (no matter which browser). They are only shown when opening the HTML-File with Windows!

This would be fixed if pasting a Screenshot in Windows would be with a Slash instead of Backslash. Is there a reason why it's a Backslash instead?

**Comment by tlnagy** [comment]
I pushed a new version (v0.1.5) that should always use the unix format for embedding in markdown. Please open a new issue if it doesn't fix your problem.
