### ISSUE TITLE
Write Image Names as Original file names ( not file destination)

### ISSUE THREAD

**Issue by elvinos** [tlnagy/atom-markdown-image-assistant#5]
Hello,

It would be great if this application allowed the uses to keep the original filename or even better choose the filename when dropped into the editor. Tried manipulating the code to see if I could create a quick and dirty edit, but haven't been successful yet.
Thanks for the plugin, very cool how it works!

**Comment by tlnagy** [comment]
What would you suggest doing for copy and pasted images? Give them the current random hex string and only preserve the name of files that already have a name?

**Comment by elvinos** [comment]
Yes, that would work well. Images on the user HD will already have a useful name. If copying and pasting it is more likely the name is from a website so has a name not already chosen by the user, therefore, less relevant. A future release may allow the user to determine which naming strategy they would like to use but for now, a simple either or would be a great enhancement.

**Comment by tlnagy** [comment]
I implemented preliminary support for this feature. The problem is that collisions are much more likely with this approach, we'll probably need some kind of file dialog to pop when a collision is detected.
